import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const baseDate = new Date('2024-01-01');
    
    const sampleProducts = [
        {
            sellerId: 'system',
            title: 'Professional Narrator Voice Pack',
            description: 'Premium voice pack featuring 5 professional narrator voices perfect for documentaries, audiobooks, and corporate videos. Includes male and female voices with neutral accents.',
            price: 1999,
            fileUrl: 'https://storage.osirix.ai/products/professional-narrator-pack.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/professional-narrator-preview.mp3',
            category: 'voice-packs',
            tags: ['professional', 'narrator', 'documentary', 'audiobook', 'neutral'],
            isPublished: true,
            salesCount: 156,
            createdAt: new Date(baseDate.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Character Voices Collection',
            description: 'Diverse collection of 10 character voices for animations, games, and creative projects. Includes fantasy characters, cartoon styles, and dramatic voices.',
            price: 2499,
            fileUrl: 'https://storage.osirix.ai/products/character-voices-collection.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/character-voices-preview.mp3',
            category: 'voice-packs',
            tags: ['character', 'animation', 'gaming', 'fantasy', 'creative'],
            isPublished: true,
            salesCount: 89,
            createdAt: new Date(baseDate.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Accent Pack - British English',
            description: 'Authentic British English voices with regional variations including RP, Cockney, Scottish, and Welsh accents. Perfect for localization and authentic UK content.',
            price: 1499,
            fileUrl: 'https://storage.osirix.ai/products/accent-pack-british.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/accent-british-preview.mp3',
            category: 'voice-packs',
            tags: ['british', 'accent', 'localization', 'uk', 'regional'],
            isPublished: true,
            salesCount: 127,
            createdAt: new Date(baseDate.getTime() + 15 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Premium Business Avatar Bundle',
            description: 'Professional avatar bundle featuring 8 high-quality business avatars in various settings. Includes both formal and smart casual styles, perfect for corporate presentations and training videos.',
            price: 4999,
            fileUrl: 'https://storage.osirix.ai/products/premium-business-avatars.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/business-avatars-preview.mp4',
            category: 'avatars',
            tags: ['business', 'professional', 'corporate', 'presentation', 'training'],
            isPublished: true,
            salesCount: 234,
            createdAt: new Date(baseDate.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Animated Character Set',
            description: 'Fun and engaging animated characters perfect for educational content, explainer videos, and social media. Includes 12 diverse animated avatars with customizable expressions.',
            price: 3999,
            fileUrl: 'https://storage.osirix.ai/products/animated-character-set.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/animated-characters-preview.mp4',
            category: 'avatars',
            tags: ['animated', 'character', 'education', 'explainer', 'social'],
            isPublished: true,
            salesCount: 178,
            createdAt: new Date(baseDate.getTime() + 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Social Media Template Pack',
            description: 'Complete social media template collection with 50+ templates optimized for Instagram, TikTok, YouTube Shorts, and Facebook. Includes trending formats and effects.',
            price: 999,
            fileUrl: 'https://storage.osirix.ai/products/social-media-templates.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/social-templates-preview.mp4',
            category: 'templates',
            tags: ['social-media', 'instagram', 'tiktok', 'youtube', 'trending'],
            isPublished: true,
            salesCount: 412,
            createdAt: new Date(baseDate.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'YouTube Intro Templates',
            description: 'Professional YouTube intro and outro templates. 25 customizable designs ranging from minimal to cinematic styles. Includes 4K versions and music tracks.',
            price: 1499,
            fileUrl: 'https://storage.osirix.ai/products/youtube-intro-templates.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/youtube-intros-preview.mp4',
            category: 'templates',
            tags: ['youtube', 'intro', 'outro', '4k', 'cinematic'],
            isPublished: true,
            salesCount: 298,
            createdAt: new Date(baseDate.getTime() + 35 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 35 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Product Demo Templates',
            description: 'Sleek product demonstration templates perfect for showcasing apps, physical products, and services. Includes 20 modern layouts with animated transitions.',
            price: 1999,
            fileUrl: 'https://storage.osirix.ai/products/product-demo-templates.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/product-demo-preview.mp4',
            category: 'templates',
            tags: ['product', 'demo', 'showcase', 'presentation', 'modern'],
            isPublished: true,
            salesCount: 186,
            createdAt: new Date(baseDate.getTime() + 40 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 40 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Corporate Office Backgrounds',
            description: 'Professional virtual office backgrounds in 4K quality. 15 modern office settings including conference rooms, executive offices, and co-working spaces.',
            price: 799,
            fileUrl: 'https://storage.osirix.ai/products/corporate-office-backgrounds.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/office-backgrounds-preview.jpg',
            category: 'backgrounds',
            tags: ['corporate', 'office', 'professional', '4k', 'virtual'],
            isPublished: true,
            salesCount: 267,
            createdAt: new Date(baseDate.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 45 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Virtual Studio Backgrounds',
            description: 'High-end virtual studio backgrounds with lighting effects. 20 broadcast-quality backgrounds perfect for news, talk shows, and professional video production.',
            price: 1299,
            fileUrl: 'https://storage.osirix.ai/products/virtual-studio-backgrounds.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/studio-backgrounds-preview.jpg',
            category: 'backgrounds',
            tags: ['studio', 'broadcast', 'news', 'production', 'lighting'],
            isPublished: true,
            salesCount: 145,
            createdAt: new Date(baseDate.getTime() + 48 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 48 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Royalty-Free Background Music Vol 1',
            description: 'Comprehensive music collection with 30 royalty-free tracks spanning multiple genres. Perfect for videos, presentations, and podcasts. Includes both full tracks and loops.',
            price: 1999,
            fileUrl: 'https://storage.osirix.ai/products/background-music-vol1.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/background-music-preview.mp3',
            category: 'music',
            tags: ['music', 'royalty-free', 'background', 'podcast', 'video'],
            isPublished: true,
            salesCount: 324,
            createdAt: new Date(baseDate.getTime() + 50 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 50 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Upbeat Intro Music Pack',
            description: 'Energetic intro music perfect for YouTube videos, podcasts, and social media content. 15 upbeat tracks in various tempos and styles, all under 30 seconds.',
            price: 1499,
            fileUrl: 'https://storage.osirix.ai/products/upbeat-intro-music.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/upbeat-intro-preview.mp3',
            category: 'music',
            tags: ['upbeat', 'intro', 'energetic', 'youtube', 'podcast'],
            isPublished: true,
            salesCount: 389,
            createdAt: new Date(baseDate.getTime() + 52 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 52 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Cinematic Transition Effects',
            description: 'Hollywood-style transition effects pack with 40+ premium transitions including glitch, sweep, zoom, and fade effects. Compatible with all major video editors.',
            price: 1799,
            fileUrl: 'https://storage.osirix.ai/products/cinematic-transitions.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/transitions-preview.mp4',
            category: 'templates',
            tags: ['cinematic', 'transitions', 'effects', 'hollywood', 'premium'],
            isPublished: true,
            salesCount: 213,
            createdAt: new Date(baseDate.getTime() + 54 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 54 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'E-Learning Course Templates',
            description: 'Complete e-learning video templates with interactive elements, quiz layouts, and lesson structures. 35 templates designed for online education and training programs.',
            price: 2799,
            fileUrl: 'https://storage.osirix.ai/products/elearning-templates.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/elearning-preview.mp4',
            category: 'templates',
            tags: ['elearning', 'education', 'training', 'interactive', 'course'],
            isPublished: true,
            salesCount: 167,
            createdAt: new Date(baseDate.getTime() + 56 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 56 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            sellerId: 'system',
            title: 'Meditation & Wellness Backgrounds',
            description: 'Serene animated backgrounds perfect for meditation videos, wellness content, and relaxation apps. 18 calming scenes with nature elements and soft animations.',
            price: 899,
            fileUrl: 'https://storage.osirix.ai/products/meditation-backgrounds.zip',
            previewUrl: 'https://storage.osirix.ai/products/previews/meditation-preview.mp4',
            category: 'backgrounds',
            tags: ['meditation', 'wellness', 'relaxation', 'nature', 'calm'],
            isPublished: false,
            salesCount: 0,
            createdAt: new Date(baseDate.getTime() + 58 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(baseDate.getTime() + 58 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});