import { db } from '@/db';
import { transactions } from '@/db/schema';

async function main() {
    const now = new Date();
    const sampleTransactions = [
        // Completed earnings - product sales
        {
            walletId: 1,
            userId: 'demo-user-1',
            type: 'earning',
            amount: 2499,
            status: 'completed',
            sourceType: 'product_sale',
            sourceId: 5,
            description: 'Product sale: Premium Avatar Bundle',
            metadata: { productId: 5, productName: 'Premium Avatar Bundle', buyerId: 'buyer-123' },
            createdAt: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            walletId: 2,
            userId: 'demo-user-2',
            type: 'earning',
            amount: 1899,
            status: 'completed',
            sourceType: 'product_sale',
            sourceId: 12,
            description: 'Product sale: AI Voice Pack Pro',
            metadata: { productId: 12, productName: 'AI Voice Pack Pro', buyerId: 'buyer-456' },
            createdAt: new Date(now.getTime() - 38 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 38 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            walletId: 5,
            userId: 'seller-user-1',
            type: 'earning',
            amount: 4999,
            status: 'completed',
            sourceType: 'product_sale',
            sourceId: 18,
            description: 'Product sale: Complete Character Studio Pack',
            metadata: { productId: 18, productName: 'Complete Character Studio Pack', buyerId: 'buyer-789' },
            createdAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            walletId: 3,
            userId: 'demo-user-3',
            type: 'earning',
            amount: 1299,
            status: 'completed',
            sourceType: 'product_sale',
            sourceId: 7,
            description: 'Product sale: Social Media Templates',
            metadata: { productId: 7, productName: 'Social Media Templates', buyerId: 'buyer-234' },
            createdAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 25 * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Completed earnings - sponsorships
        {
            walletId: 4,
            userId: 'creator-user-1',
            type: 'earning',
            amount: 3500,
            status: 'completed',
            sourceType: 'sponsorship',
            sourceId: null,
            description: 'Sponsorship payment - TechCorp Q1 Campaign',
            metadata: { sponsorName: 'TechCorp', campaign: 'Q1-2024', deliverables: 3 },
            createdAt: new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 50 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            walletId: 1,
            userId: 'demo-user-1',
            type: 'earning',
            amount: 2800,
            status: 'completed',
            sourceType: 'sponsorship',
            sourceId: null,
            description: 'Sponsorship payment - CreativeTools Brand Partnership',
            metadata: { sponsorName: 'CreativeTools', campaign: 'Launch-2024', contentPieces: 5 },
            createdAt: new Date(now.getTime() - 40 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            walletId: 2,
            userId: 'demo-user-2',
            type: 'earning',
            amount: 4200,
            status: 'completed',
            sourceType: 'sponsorship',
            sourceId: null,
            description: 'Sponsorship payment - AIStudio Annual Deal',
            metadata: { sponsorName: 'AIStudio', campaign: 'Annual-2024', duration: 'monthly' },
            createdAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 20 * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Completed earnings - affiliate
        {
            walletId: 3,
            userId: 'demo-user-3',
            type: 'earning',
            amount: 850,
            status: 'completed',
            sourceType: 'affiliate',
            sourceId: null,
            description: 'Affiliate commission - Q1 Performance',
            metadata: { affiliateCode: 'AFF123', tier: 'gold', conversions: 15 },
            createdAt: new Date(now.getTime() - 35 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 35 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            walletId: 5,
            userId: 'seller-user-1',
            type: 'earning',
            amount: 1250,
            status: 'completed',
            sourceType: 'affiliate',
            sourceId: null,
            description: 'Affiliate commission - Premium Referrals',
            metadata: { affiliateCode: 'PREM456', tier: 'platinum', conversions: 22 },
            createdAt: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Completed earnings - service
        {
            walletId: 4,
            userId: 'creator-user-1',
            type: 'earning',
            amount: 3200,
            status: 'completed',
            sourceType: 'service',
            sourceId: null,
            description: 'Custom avatar creation service',
            metadata: { serviceType: 'custom_avatar', clientId: 'client-789', hoursWorked: 8 },
            createdAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Completed earnings - marketplace
        {
            walletId: 2,
            userId: 'demo-user-2',
            type: 'earning',
            amount: 750,
            status: 'completed',
            sourceType: 'marketplace',
            sourceId: null,
            description: 'Marketplace transaction - Design Assets',
            metadata: { marketplaceName: 'CreatorHub', itemsSold: 3, category: 'design' },
            createdAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Withdrawals - completed
        {
            walletId: 1,
            userId: 'demo-user-1',
            type: 'withdrawal',
            amount: 5000,
            status: 'completed',
            sourceType: 'service',
            sourceId: null,
            description: 'Bank transfer withdrawal',
            metadata: { method: 'bank_transfer', accountLast4: '4567', processingFee: 50 },
            createdAt: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 22 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            walletId: 4,
            userId: 'creator-user-1',
            type: 'withdrawal',
            amount: 8500,
            status: 'completed',
            sourceType: 'service',
            sourceId: null,
            description: 'PayPal withdrawal',
            metadata: { method: 'paypal', email: 'creator@example.com', processingFee: 85 },
            createdAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 12 * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Pending withdrawals
        {
            walletId: 5,
            userId: 'seller-user-1',
            type: 'withdrawal',
            amount: 3500,
            status: 'pending',
            sourceType: 'service',
            sourceId: null,
            description: 'Stripe withdrawal - pending review',
            metadata: { method: 'stripe', processingFee: 35, estimatedArrival: '2024-12-30' },
            createdAt: new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            walletId: 3,
            userId: 'demo-user-3',
            type: 'withdrawal',
            amount: 2200,
            status: 'pending',
            sourceType: 'service',
            sourceId: null,
            description: 'Bank transfer - awaiting approval',
            metadata: { method: 'bank_transfer', accountLast4: '8901', submittedAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString() },
            createdAt: new Date(now.getTime() - 1 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 12 * 60 * 60 * 1000).toISOString(),
        },
        
        // Bonuses
        {
            walletId: 1,
            userId: 'demo-user-1',
            type: 'bonus',
            amount: 500,
            status: 'completed',
            sourceType: 'service',
            sourceId: null,
            description: 'New creator welcome bonus',
            metadata: { bonusType: 'welcome', reason: 'New account signup' },
            createdAt: new Date(now.getTime() - 55 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 55 * 24 * 60 * 60 * 1000).toISOString(),
        },
        {
            walletId: 4,
            userId: 'creator-user-1',
            type: 'bonus',
            amount: 300,
            status: 'completed',
            sourceType: 'service',
            sourceId: null,
            description: 'Milestone achievement bonus - 100 sales',
            metadata: { bonusType: 'milestone', milestone: '100_sales', achievements: ['top_seller'] },
            createdAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 18 * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Refund
        {
            walletId: 2,
            userId: 'demo-user-2',
            type: 'refund',
            amount: 450,
            status: 'completed',
            sourceType: 'service',
            sourceId: null,
            description: 'Service fee refund - technical issue',
            metadata: { refundReason: 'technical_issue', originalTransaction: 'txn_abc123', issueType: 'processing_error' },
            createdAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        },
        
        // Failed transaction
        {
            walletId: 3,
            userId: 'demo-user-3',
            type: 'withdrawal',
            amount: 1500,
            status: 'failed',
            sourceType: 'service',
            sourceId: null,
            description: 'Withdrawal failed - insufficient balance',
            metadata: { method: 'bank_transfer', failureReason: 'insufficient_balance', attemptedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString() },
            createdAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
            updatedAt: new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        },
    ];

    await db.insert(transactions).values(sampleTransactions);
    
    console.log('✅ Transactions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});